spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.40.131/sell?characterEncoding=utf-8&useSSL=false&ServerTimezone=UTC
  jpa:
    show-sql: true
server:
  servlet:
    context-path: /sell