spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.40.131/sell?characterEncoding=utf-8&useSSL=false&ServerTimezone=UTC
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
#server:
#  servlet:
#    context-path: /sell
wechat:
  mpAppId: wxfcbdc67c88356272
  mpAppSecret: 9511982ca4050a1aff8fc88ebf8862d3

